version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(levelname)s][%(name)s][%(threadName)s]: %(message)s\n"
    detail:
        format: "%(asctime)s - [%(levelname)s][%(name)s][%(threadName)s]: %(message)s"
        datefmt: '%m/%d/%Y %I:%M:%S %p'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file_info:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detail
        filename: app.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO
    handlers: [console, file_info]
